FROM python:3.11-slim

WORKDIR /app

ARG ENVIRONMENT=dev
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_ENV=${ENVIRONMENT}

COPY requirements/${ENVIRONMENT}.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8000

# Use different commands based on environment
CMD if [ "$DJANGO_ENV" = "prod" ]; then \
        gunicorn core.wsgi:application --bind 0.0.0.0:8000; \
    else \
        python manage.py runserver 0.0.0.0:8000; \
    fi
